### ISSUE TITLE
No primitive-math namespace defined

### ISSUE THREAD

**Issue by triss** [kunstmusik/music-examples#1]
Both `example2-basic` and `example2-advanced` namespaces require the non existant `primitive-math` namespace resulting in the following error being thrown:

`!!CompilerException java.io.FileNotFoundException: Could not locate primitive_math__init.class or primitive_math.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:`

**Comment by kunstmusik** [comment]
Thanks @triss for reporting this, I've made the same change (I had replaced primitive-math with just not== in pink.util in 0.2.1, and had forgotten to update the music-examples for this).
